name: First Test

on:
    push:
        branches: ["main"]

jobs:
    etbentantpis:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Node Setup
              uses: actions/setup-node@v3
              with:
                node-version: 18.x
            - name: Run Blague
              run: echo Ben tant pis

    route:
        needs: [etbentantpis]
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: 18.x
            - name: Install dependancies
              run: npm ci
            - name: Route test
              run: npm run test
